name: flutter_all_in_one
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  go_router: ^14.7.2
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.1
  connectivity_plus: ^6.1.2
  injectable: ^2.5.0
  dio: ^5.8.0+1

  # Firebase
  firebase_core: ^3.10.1
  firebase_remote_config: ^5.3.1

  # UI Helper
  icons_plus: ^5.0.0
  package_info_plus: ^8.1.4
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - asset/
