// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP13Gk0L3MONiILMN72DfcGChGtw4soyo',
    appId: '1:729644045218:web:ef6229217ce547f9dd98fb',
    messagingSenderId: '729644045218',
    projectId: 'flutter-all-in-one-39dc9',
    authDomain: 'flutter-all-in-one-39dc9.firebaseapp.com',
    storageBucket: 'flutter-all-in-one-39dc9.firebasestorage.app',
    measurementId: 'G-DXEFFSTX9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9hvYOhgLtCNc5NBk9YlgwfziyJHiMjQI',
    appId: '1:729644045218:android:fb6890f7f990fdd1dd98fb',
    messagingSenderId: '729644045218',
    projectId: 'flutter-all-in-one-39dc9',
    storageBucket: 'flutter-all-in-one-39dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3QyAxqn9pTdjzAPLJRcyExBjk1w2LNpU',
    appId: '1:729644045218:ios:fab03ee179abfcacdd98fb',
    messagingSenderId: '729644045218',
    projectId: 'flutter-all-in-one-39dc9',
    storageBucket: 'flutter-all-in-one-39dc9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAllInOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3QyAxqn9pTdjzAPLJRcyExBjk1w2LNpU',
    appId: '1:729644045218:ios:fab03ee179abfcacdd98fb',
    messagingSenderId: '729644045218',
    projectId: 'flutter-all-in-one-39dc9',
    storageBucket: 'flutter-all-in-one-39dc9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAllInOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP13Gk0L3MONiILMN72DfcGChGtw4soyo',
    appId: '1:729644045218:web:b007457b2a115617dd98fb',
    messagingSenderId: '729644045218',
    projectId: 'flutter-all-in-one-39dc9',
    authDomain: 'flutter-all-in-one-39dc9.firebaseapp.com',
    storageBucket: 'flutter-all-in-one-39dc9.firebasestorage.app',
    measurementId: 'G-KY4WB4RSLL',
  );
}
